### PR TITLE
Copy components values to keep original request not modified.

### PR DESCRIPTION
**Pull request by AlphaWong**
# Reference
closes https://github.com/googlemaps/google-maps-services-go/issues/208

### CODE REVIEW

**Comment by AlphaWong** [comment]
@googlebot  I fixed it.

**Comment by jpoehnelt** [comment]
@kirylandruski mind signing the CLA above?

**Comment by AlphaWong** [comment]
@googlebot I fixed it.

**Comment by jpoehnelt** [comment]
@kirylandruski your signing of the contributor's license is required to merge this pull request.

**Comment by kirylandruski** [comment]
@googlebot I fixed it

**Comment by AlphaWong** [comment]
> @googlebot I fixed it

I think u need to click https://cla.developers.google.com/ to sign the CLA

**Comment by kirylandruski** [comment]
> > @googlebot I fixed it
> 
> I think u need to click https://cla.developers.google.com/ to sign the CLA

It looks like it's already signed

**Comment by kirylandruski** [comment]
@googlebot I fixed it.

**Comment by jpoehnelt** [comment]
I rebased and merged that one. Closing this.

**Pull request closed without merging**
