### PR TITLE
add Static Map service

### PR DESCRIPTION
**Pull request by jgsqware**
Add this service https://developers.google.com/maps/documentation/static-maps/intro

### CODE REVIEW

**Comment by jgsqware** [comment]
I signed it!

**Comment by domesticmouse** [comment]
I'm not going to merge a PR with a failing Travis build. On the upside, I've uplifted the tested versions of Go to 1.7.x, 1.8.x and tip. Can you merge that change into your PR and see if that fixes your travis build?

**Comment by domesticmouse** [comment]
Please add tests. Thanks!

**Comment by superstas** [comment]
@jgsqware this is so helpful PR. I'm looking forward to using it. Will you fix for merging it?

**Comment by domesticmouse** [comment]
I'm going to land this change and then add tests. Thanks!

**Comment by jgsqware** [comment]
Thanks! Glad to help. Will look forward for test also

**Comment by domesticmouse** [comment]
I added test coverage with https://github.com/googlemaps/google-maps-services-go/pull/108 =)

**Pull request merged**
