### PR TITLE
allow closing channel to release go routine of rate limiting

### PR DESCRIPTION
**Pull request by BorisBorshevsky**

### CODE REVIEW

**Comment by BorisBorshevsky** [comment]
I signed it!

**Comment by domesticmouse** [comment]
Thanks!

**Comment by igtm** [comment]
@domesticmouse 
When can i use this method `Close` ?
[googlemaps.github.io/maps](https://godoc.org/googlemaps.github.io/maps) doesn't seem to sync with master branch of this repository.

**Comment by domesticmouse** [comment]
This changed was merged, and then deleted in https://github.com/googlemaps/google-maps-services-go/pull/133 where we eliminated the rate limiting go-routine entirely.

**Comment by igtm** [comment]
oh, I didn't notice #133 . Thanks!

**Pull request merged**
