### PR TITLE
Add go mod support

### PR DESCRIPTION
**Pull request by kahuang**

### CODE REVIEW

**Comment by kahuang** [comment]
@googlebot I signed it!

**Comment by kahuang** [comment]
I can remove the /vendor directory if you guys prefer

**Comment by wendyadi** [comment]
I'm not a maintainer but i think `vendor/` directory should be omitted.
Such in:
https://github.com/jmoiron/sqlx and https://github.com/rsc/qr

@kahuang 
cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @jpoehnelt

**Pull request closed without merging**
